version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/rakusuke
      - node_modules:/workspaces/rakusuke/node_modules
      - app_web_next:/workspaces/rakusuke/apps/web/.next
    working_dir: /workspaces/rakusuke
    tty: true
    ports:
      - ${DEV_PORT_WEB:-3000}:3000
      - ${DEV_PORT_SERVER:-3001}:3001
      - ${DEV_PORT_STORYBOOK:-6006}:6006
      - ${DEV_PORT_PRISMA_STUDIO:-5555}:5555
    environment:
      - TZ=${TZ:-}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=public&connect_timeout=10
      - PEPPER_USER=${PEPPER_USER:-dev}
      - PEPPER_EVENT=${PEPPER_EVENT:-dev}
      - NEXT_PUBLIC_URL_API=http://localhost:3001
      - URL_APP=http://localhost:3000
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on

volumes:
  node_modules:
  app_web_next:
  db-store:
