name: Migrate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16"

      - name: Set env for staging
        if: ${{ inputs.environment == 'staging' }}
        run: |
          echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" >> $GITHUB_ENV

      - name: Set env for production
        if: ${{ inputs.environment == 'production' }}
        run: |
          echo "DATABASE_URL=${{ secrets.PRODUCTION_DATABASE_URL }}" >> $GITHUB_ENV

      - name: Install Dependencies

        run: |
          npm install -g turbo@1.10.3 prisma@4.15.0
          rm -rf ./apps
          rm -rf ./packages
          npm ci --ignore-scripts

      - name: Build
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: prisma generate

      - name: Deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: prisma migrate deploy
