name: staging deploy to S3
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Before Install
        run: |
          rm -rf ./apps/workshop
          rm -rf ./apps/server
          rm -rf ./apps/edge

      - name: Install Dependencies
        run: yarn workspace web install

      - name: Build
        run: |
          yarn workspace web build-static
          rm -rf ./apps/web/out/e/\[p\]/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ENV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region us-east-1 ./apps/web/out s3://${{ secrets.STAGING_AWS_S3_BUCKET }} --delete
          echo "AWS CF reset"
          aws cloudfront create-invalidation --region us-east-1 --distribution-id ${{ secrets.STAGING_AWS_CF_ID }} --paths "/*"
